@startuml
top to bottom direction

package "Presentation Layer" {
}
package "Application Layer" {
}
package "Domain Layer" {
}
package "Infrastructure Layer" {
}

"Presentation Layer" --> "Application Layer"
"Application Layer" --> "Domain Layer"
"Infrastructure Layer" -u-> "Domain Layer"

package "AppBoot Layer" {
}

"AppBoot Layer" .l.> "Presentation Layer"
"AppBoot Layer" .l.> "Application Layer"
"AppBoot Layer" .l.> "Domain Layer"
"AppBoot Layer" .l.> "Infrastructure Layer"
@enduml
